### ISSUE TITLE
Lots of circular dependencies in package

### ISSUE THREAD

**Issue by briankellydev** [chrispaterson/iabtcf#30]
Hello all- having installed this package in an existing product, when I run my production build it's flagging a large number of circular dependencies in the iabtcf package. Here's a list of them for your reference:

Circular dependency: node_modules/@iabtcf/core/lib/model/index.js -> node_modules/@iabtcf/core/lib/model/PurposeRestrictionVector.js -> node_modules/@iabtcf/core/lib/model/index.js
Circular dependency: node_modules/@iabtcf/core/lib/model/index.js -> node_modules/@iabtcf/core/lib/model/PurposeRestrictionVector.js -> commonjs-proxy:/Users/briankelly/Documents/projects/cookie-banner-sdk/node_modules/@iabtcf/core/lib/model/index.js -> node_modules/@iabtcf/core/lib/model/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/CoreTCEncoder.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/CoreTCEncoder.js -> commonjs-proxy:/Users/briankelly/Documents/projects/cookie-banner-sdk/node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/DateEncoder.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/EncoderMap.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/FixedVectorEncoder.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/LangEncoder.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/PurposeRestrictionVectorEncoder.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/SegmentEncoderMap.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/VendorVectorEncoder.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/VendorsDisclosedEncoder.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/VendorsAllowedEncoder.js -> node_modules/@iabtcf/core/lib/encoder/index.js
Circular dependency: node_modules/@iabtcf/core/lib/encoder/index.js -> node_modules/@iabtcf/core/lib/encoder/PublisherTCEncoder.js -> node_modules/@iabtcf/core/lib/encoder/index.js

**Comment by chrispaterson** [comment]
Interesting.  I've been using an index.js at the base of each "package" to make it so that I can do imports like:

```javascript
import {MyClass} from "./"
```

What is giving you this output?

**Comment by chrispaterson** [comment]
I pushed an update to the code to not use "barrel" imports which cause this circular dependency issue.
